### PR TITLE
Update deprecated grpc dependency to @grpc/grpc-js

### LINKED ISSUE #1741: Use @grpc/grpc-js instead of grpc JavaScript dependency
Currently the [grpc package is deprecated](https://www.npmjs.com/package/grpc) is deprecated. It is used in a few places (`messages`, `back` and `pusher`). It should be replaced by the drop-in replacement [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js).

As a bonus, this newer package is pure JavaScript and thus doesn't require building or fetching native binaries, improving the build process by a lot.

### PR DESCRIPTION
**Pull request by rien**
Fixes #1741. 

- [x] messages
- [x] front
- [x] back
- [x] pusher

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @rien,

Thanks so much for this PR.
It looks good to me! We are currently facing issues on our continuous deployment environment that prevents me from testing this properly but I'll merge this as soon as I had the opportunity to test it.

And thanks a lot for pinpointing the error with the bad `emitError` call!

**Comment by moufmouf** [comment]
@gparant I need some help to understand what is going on here.
I'm very much willing to merge this, but currently, the code is broken.

You can test this locally, there is a call to /login-callback performed (even in "self-hosted mode") and I don't understand why it is failing. It seems the pusher tries to connect to an OpenId connect provider but that none has been passed in parameter.

The funny thing is that the error I see does not seem related to changes performed by @rien. Any idea of what could be going wrong?

**Comment by rien** [comment]
I am having the same problems while trying to deploy workadventure. If you look at the WebSocket connection there is only one message `cannot read properties of undefined (reading 'credentials')` so it may have something to do with gRPC.

I will try to revert my changes to see if that works, but it would be good if someone else could look at this with more experience.

**Comment by rien** [comment]
I am retracting this PR since Workadventure is considering adding support for NFT's. :disappointed: 

Please reconsider this decision. NFT's are a harmful technology for our society as a whole and they are inherently flawed.

**Pull request closed without merging**
