### PR TITLE
Remove .htaccess as it's no longer in use 

### PR DESCRIPTION
**Pull request by bufferoverflow**
Yes, it's not in use for nginx. 

However, it's available within public folder and therefore detected by security scanners.

### CODE REVIEW

**Comment by lukashass** [comment]
We can just remove the .htaccess instead :wink:

**Comment by moufmouf** [comment]
:+1: for removing the .htaccess. It ain't used anymore!

**Comment by bufferoverflow** [comment]
thanks @lukashass and @moufmouf I was unsure if `.htaccess` is still in use, now it's clear. I updated this PR to just remove it.

**Comment by moufmouf** [comment]
Thanks! :+1:

**Pull request merged**
