### PR TITLE
Bundle nes.css and quill-js

### LINKED ISSUE #1842: Please remove external ressources
For privacy and stability reasons, I would be really happy if all external ressources could be directly hosted by WorkAdventure itself and not link to external ressources. 
I found this two to be linking outside of our domain: 
- https://unpkg.com/nes.css@2.3.0/css/nes.min.css
- https://cdn.quilljs.com/1.3.7/quill.snow.css

Especially with the context of GDPR external ressources embedded like this can cause privacy issues. That's why embedding Google fonts for instance is not recommended anymore: 

https://www.golem.de/news/landgericht-muenchen-einbindung-von-google-fonts-ist-rechtswidrig-2202-162826.html

"A Munich Regional Court judge has ruled that the integration of dynamic web content such as Google Fonts from US web services is illegal without the consent of the visitor. The ruling stated that there is no legitimate interest within the meaning of the General Data Protection Regulation (GDPR), because the Google Fonts can be downloaded and delivered from your own server instead of integrating them via external Google servers. The website operator faces a fine of up to 250,000 euros or imprisonment for up to six months if the plaintiff's IP address is passed on to Google when the website is visited.
While this judgement is about the integration of Google fonts specifically, the principles established by the court also apply to all other content from US services integrated externally into websites. If the ruling stands, any content served by a CDN would be affected. To avoid violating the law, websites must host content such as fonts, scripts or images themselves. Alternatively, website hosts could obtain consent to the disclosure of the IP address via a consent banner."

### PR DESCRIPTION
**Pull request by anbraten**
Closes #1842

### CODE REVIEW

**Comment by moufmouf** [comment]
Thanks a lot @anbraten !

It definitely looks good!

It seems you commited back the file `front/dist/index.tmpl.html.tmp` which is a file we used in the previous releases but that has been removed (it is replaced by `index.ejs`).

Could you remove this file please?

**Comment by anbraten** [comment]
@moufmouf Ohh missed that. I adjusted it. Should be fine now.

**Comment by moufmouf** [comment]
Hey @anbraten ,

I've been testing Quill (you might have a hard time testing it without a working admin interface) and it seems there are issues (I guess it is with the CSS):

image

It seems related to the CSS not loading at all:

image

If you have any idea where this could come from, don't hesitate to have a look. I guess you can't easily test this without a working admin interface so if nothing is obvious to you, I'll try to fix it myself next week!

Thanks again for your help.

**Comment by pizkaz** [comment]
`@import "~/foobar"` does not seem to work in Svelte. If we import it in `style/TextGlobalMessageSvelte-Style.scss`, as show in the attached patch, it works.

[patch.txt](https://github.com/thecodingmachine/workadventure/files/8055985/patch.txt)

**Pull request merged**
