### PR TITLE
added optino to open a new tab

### PR DESCRIPTION
**Pull request by jonnytest1**
https://github.com/thecodingmachine/workadventure/issues/1268

### CODE REVIEW

**Comment by Kharhamel** [comment]
Sorry I missed this PR. This sounds like a good idea. Do you think you can solve the various conflicts?

**Comment by jonnytest1** [comment]
u knwo what ill recreate it (i also did some other chagnes[that are overcomplicated for the task or dont really apply anymore])

**Comment by jonnytest1** [comment]
@Kharhamel https://github.com/thecodingmachine/workadventure/pull/1405

**Comment by Kharhamel** [comment]
Good idea, the new PR is much cleaner. I will close this one

**Pull request closed without merging**
