### PR TITLE
Exit scene acess denied detected

### PR DESCRIPTION
**Pull request by gparant**
Permit to check access on "exitUrl" properties. Il user haven't access we show error message

### CODE REVIEW

**Comment by jonnytest1** [comment]
dont forget to implement the denial basckend side as well - its pretty easy to circumvent frontend permission checks

**Comment by gparant** [comment]
@jonnytest1 thanks for your feedback, don't worry the security check was developed in our Back Office 🚀

**Comment by Moini** [comment]
I get this error when the map doesn't load for some reason, even though it should be working. Possibly to do with change to exitUrl.

**Comment by Moini** [comment]
(btw. suggesting to fix the English grammar on the denial sentence: "Room access denied. You don't have permission to access this room.")

**Pull request merged**
