### PR TITLE
store "muted" state of audio player in local store

### PR DESCRIPTION
**Pull request by tabascoeye**
The state of "muted" of the AudioPlayer should be stored in localStore just as the volume level is storeg already.

(I also renamed the key for the volume so that is is more unique)

### CODE REVIEW

**Review by Kharhamel — CHANGES_REQUESTED** [review]
Please put every reference to localStorage in the dedicated class LocalUserStore.

**Comment by tabascoeye** [comment]
I copied from the way the "volume" is already stored in localUserStore. You're saying that is already wrong?

**Comment by Kharhamel** [comment]
Yes. There is some shaddy code in wa like in all projects. Some people don't mind having localStorage (or other important global objects) accesses hidden in all the project, even though it is a big code smell.

**Comment by tabascoeye** [comment]
whops. Something went wrong merging. Closing this and will reopen a new PR. Sorry about that

**Pull request closed without merging**
