### PR TITLE
Fixing docker-compose single domain install

### PR DESCRIPTION
**Pull request by moufmouf**
Making it use play container
Making it use prod image (instead of old images)
Allowing relative URLs in environment variables

### CODE REVIEW

**Comment by nextgen-networks** [comment]
@moufmouf Play container crashes on my test-server when applying your changes to current develop branch.

Here is the log output:
play_1           | yarn run v1.22.19
play_1           | $ node -r source-map-support/register --max-old-space-size=4096 ./dist/server.js
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/xmpp`), the TLS options applied for this router will depend on the SNI of each request" entryPointName=websecure routerName=ejabberd-ssl@docker
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/icon`), the TLS options applied for this router will depend on the SNI of each request" entryPointName=websecure routerName=icon-ssl@docker
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/`), the TLS options applied for this router will depend on the SNI of each request" entryPointName=websecure routerName=play-ssl@docker
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/api`), the TLS options applied for this router will depend on the SNI of each request" routerName=back-ssl@docker entryPointName=websecure
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/chat`), the TLS options applied for this router will depend on the SNI of each request" routerName=chat-ssl@docker entryPointName=websecure
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/uploader`), the TLS options applied for this router will depend on the SNI of each request" routerName=uploader-ssl@docker entryPointName=websecure
reverse-proxy_1  | time="2022-11-13T17:45:57Z" level=warning msg="No domain found in rule PathPrefix(`/map-storage`), the TLS options applied for this router will depend on the SNI of each request" entryPointName=websecure routerName=map-storage-ssl@docker
play_1           | Errors found in environment variables:
play_1           | For variable "PUSHER_URL": Invalid url
play_1           | For variable "UPLOADER_URL": Invalid url
play_1           | For variable "ICON_URL": Invalid url
play_1           | For variable "CHAT_URL": Invalid url
play_1           | error Command failed with exit code 1.
play_1           | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
workadventure_play_1 exited with code 1

**Comment by moufmouf** [comment]
@nextgen-networks Oh gee! You are right. We still need to specify a DOMAIN with the single-domain install for Let's encrypt to be able to get a SSL certificate.

That should be fixed. I must admit I haven't had time to test this yet.

**Comment by pharindoko** [comment]
Hey @moufmouf, any update on this ?

**Comment by moufmouf** [comment]
Hey @pharindoko ,

Could I ask you to test with this branch and let me know if it works for you?

**Pull request merged**
