### PR TITLE
fix multi user videochat mode

### PR DESCRIPTION
**Pull request by t10r**
On a videochat with four users one screen gets cut off at the bottom.

### CODE REVIEW

**Comment by Kharhamel** [comment]
Nice, i will try to test that this evening

**Comment by moufmouf** [comment]
Hey @t10r,

Thanks a lot for the PR. I'm sorry but I tried to test you PR and I can't see what it fixes.
I'm pretty sure you did this for a good reason and the code seems ok, but I don't understand what it fixes.

Could you please add in the comments 2 screenshots? One before your fix and one after, so I can understand what is going on?

Thanks!

**Comment by t10r** [comment]
Did you tried it with four people?

image

**Comment by moufmouf** [comment]
Ok! I understand now.
Sorry, I previously did not understand that you switched in "chat" mode.

Thanks a lot for the PR, it is great!

**Pull request merged**
