### PR TITLE
audio player volume improvements

### PR DESCRIPTION
**Pull request by Lurkars**
Some small improvements in UI of audioplayer
- set volume slider to 0 on mute
- unmute on change of slider
- icon indication of volume level by hiding bars on lower level
I think this adds a more intuitive use of audioplayer volume as known by native player for example.

_Disclaimer: I did not test if this is in conflict with talking reduction, but from my code perspective it shouldn't._

### CODE REVIEW

**Comment by Lurkars** [comment]
@moufmouf and @Kharhamel  what about this? Is a small but I think intuitive improvement.

**Comment by Lurkars** [comment]
(bump) I have this in production since PR here and it seems to work like charm.

**Comment by Lurkars** [comment]
@gparant @GRL78 I migrated my changes to new svelte code. Had to embed svg image directly, because otherwise it gets decoded as base64.

**Comment by Kharhamel** [comment]
I will try to test this once this is deployed

**Comment by Kharhamel** [comment]
Ok correction I cannot deploy your PR since you created from your fork. Can you show me some screenshots of the new visuals?

**Comment by Lurkars** [comment]
I merged the latest dev, does this help? Otherwise I can try to make a video, because you won't see the full changes in screens.

**Comment by Lurkars** [comment]
This is really small improvement, but I think it's more intuitive because most audio players on web work like this:
 

https://user-images.githubusercontent.com/2760570/131720667-6749c5c9-1be0-44b5-8c09-061e968472fb.mp4

**Comment by Lurkars** [comment]
@Kharhamel did you take a look?

**Comment by Kharhamel** [comment]
Yes this looks good! I think I will merge this once the CI is done.

**Comment by Kharhamel** [comment]
Done. Thank you for your help. This should be deployed next week

**Pull request merged**
