### PR TITLE
immutableData was never assigned

### PR DESCRIPTION
**Pull request by jonnytest1**
@GRL78

### CODE REVIEW

**Comment by GRL78** [comment]
@jonnytest1 Why making immutableData a promise and not just assign the payloadData to it in the callback function ?

**Comment by jonnytest1** [comment]
Because we'd need to create a new promise every time the method gets called 
It's not a h huge benefit compared to assigning but I think the code is a bit cleaner

**Comment by GRL78** [comment]
@jonnytest1 ok thanks for your explanation

**Comment by moufmouf** [comment]
:+1:

**Pull request merged**
