### PR TITLE
Revert modifcations on PUSHER_URL env

### PR DESCRIPTION
**Pull request by nolway**

### CODE REVIEW

**Comment by LindezaGrey** [comment]
@nolway i think this destroyed the single-domain compose file completely:

https://github.com/thecodingmachine/workadventure/blob/bfcb8d1600f84e3af6d07f37b403c2f251131d31/contrib/docker/docker-compose.single-domain.yaml#L1-L35

**Comment by LindezaGrey** [comment]
@moufmouf i mentionend this in the talk today

**Comment by moufmouf** [comment]
Wait, this is actually normal, no?

We changed the docker-compose single domain file to be a simple extension of the main "prod" file. This way, that's less maintenance burden (and therefore less bugs) for us.

See https://github.com/thecodingmachine/workadventure/tree/develop/contrib/docker#single-domain-install

Or did I miss something?

**Comment by LindezaGrey** [comment]
@moufmouf  oh wow the docs changed as well! :D my bad! makes sense then. I was used to either take the single domain file or the prod.

**Pull request merged**
