### PR TITLE
Typed api events

### PR DESCRIPTION
**Pull request by jonnytest1**
only type updates
provided type safety for api events 

i think there will be a future pull request that turns all message streams into promises for better feedback for the calling script as well

### CODE REVIEW

**Comment by jonnytest1** [comment]
@moufmouf youre now my default pull request person ^^

**Comment by moufmouf** [comment]
This is absolutely excellent!
Thanks a lot, I learnt so much regarding typing in Typescript reading this PR :heart:

**Comment by jonnytest1** [comment]
> This is absolutely excellent!
> Thanks a lot, I learnt so much regarding typing in Typescript reading this PR ❤️

lol this is just the beginning :D

**Comment by jonnytest1** [comment]
🤔  i wonder should we enforce that the event.type string has the same value as the method name ?

**Pull request merged**
