### PR TITLE
Create banner for Scripting API

### PR DESCRIPTION
**Pull request by gparant**
open-banner

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @gparant ,

This seems very specific to me and maybe not needed?

We have UIWebsites that can be placed wherever we want.
You could create a UIWebsite placed at the top of the screen that would act as a banner.

And as a bonus, you can put anything in a UIWebsite, you can control the text, images, position of links, etc... because it is pure HTML.

Do you see a use case for this banner that cannot be filled by a UIWebsite?

**Comment by gparant** [comment]
> 



> Hey @gparant ,
> 
> This seems very specific to me and maybe not needed?
> 
> We have UIWebsites that can be placed wherever we want. You could create a UIWebsite placed at the top of the screen that would act as a banner.
> 
> And as a bonus, you can put anything in a UIWebsite, you can control the text, images, position of links, etc... because it is pure HTML.
> 
> Do you see a use case for this banner that cannot be filled by a UIWebsite?

Yes because with UIWebsite we must open an iframe and I don't have url link web page for my need

**Comment by moufmouf** [comment]
> @moufmouf yes because with UIWebsite we must open an iframe and I don't have url link web page for my need

I don't get it. The scripting API has a `WA.nav.goToPage` to open a page instead of WorkAdventure and a `WA.nav.openTab` to open a new tab. So you can definitely follow a link from a banner opened with a UIWebsite.

**Comment by gparant** [comment]
> > @moufmouf yes because with UIWebsite we must open an iframe and I don't have url link web page for my need
> 
> I don't get it. The scripting API has a `WA.nav.goToPage` to open a page instead of WorkAdventure and a `WA.nav.openTab` to open a new tab. So you can definitely follow a link from a banner opened with a UIWebsite.

Of course, but I haven't website url to create my UIWebsite at the top.

Screenshot 2023-01-13 at 10 32 01

So we haven't embedable website, just a simple banner created by scripting API with one text and one redirect, if necessary, will be realy cool

**Pull request merged**
