### PR TITLE
WIP: Integrate with BigBlueButton

### PR DESCRIPTION
**Pull request by znerol**
Addresses: #465 

- [x] Implement property change handler for new `bbbRoom` property in `GameScene`.
- [x] Add necessary messages in protocol in `messages.proto`.
- [x] Add stub handlers in both backends (`pusher` and `back`). Returns stub join url to client.
- [x] Add stub frontend in `BbbFactory.ts`. Logs stub join url received from backend to console.
- [ ] Proper backend implementation which creates a meeting via BBB API if necessary and generates the join url.
- [ ] Proper frontend which either loads the join url in an `iframe` or displays a button to open BBB in a new tab.

### CODE REVIEW

**Comment by lunar-debian** [comment]
I have been working on this too. I'll try to publish a branch today.

**Comment by znerol** [comment]
Oh cool! Let's join forces then. I'm still a bit unsure on how to inject the room configuration into `pusher` and `back`.

**Comment by lunar-debian** [comment]
See #602. It’s not working yet. I'm just publishing early to avoid duplicating our efforts. :)

**Comment by znerol** [comment]
Closing in favor of #602.

**Pull request closed without merging**
