### PR TITLE
Adding optimization to render tiles more quickly 

### PR DESCRIPTION
**Pull request by moufmouf**
This PR adds a new optimization.
It is built on top of #911 

Tiles are now not rendered directly on screen, but in 2 intermediate textures (one for the floor and one for elements above players)
The textures are then rendered.
While this adds an extra layer, the good thing is that the textures don't need to be redrawn unless we move!

This means that we can completely bypass the drawing of each single tile most of the time (and only draw the big texture instead).

As a result, CPU consumption goes from ~50% to ~25% (this is a big boost).

Beware, this optimization will make implementing animations slightly trickier.
We will probably want to isolate tiles and not draw them in the texture but keep drawing them directly on screen.

### CODE REVIEW

**Comment by tabascoeye** [comment]
You're building custom double buffering. I almost can't imagine that phaser does not already have support and functions for that while still handling animated tiles

**Comment by moufmouf** [comment]
Hey @tabascoeye ,

Suprisingly, I fail to see in Phaser a way to handle "dirty" flags for marking objects that needs to be rerendered.
And the simple fact that I'm avoiding doing some culling of the tiles on each frame seems to improve performance somehow.

But I would die to find a simpler way to do this. If you have any idea, don't hesitate to share.
This is also maybe something that could be contributed back to Phaser if it does not exist there yet.

**Comment by moufmouf** [comment]
Detected bug:

- [ ] When starting on a new map, the character player is not displayed. We need to move to have the sprite displayed.

**Comment by moufmouf** [comment]
Cancelled: after measuring energy consumption, this change does not bring enough benefits to justify the additional maintenance complexity.
See https://thecodingmachine.io/energy-consumption-web-game-engine#scrollNav-8

**Pull request closed without merging**
