### PR TITLE
Mobile/touch support

### PR DESCRIPTION
**Pull request by pizkaz**
This combined work by @Palid, @tabascoeye and @pizkaz integrates a software joystick and adds touch support to login scenes.
With this patch set it is possible to use Workadventure on touch devices. \o/

Contrary to what commit metadata says, @Palid did most of the work for rC3. @TabascoEye and myself maintained the patches, tweaked stuff and implemented touch support for Jitsi/openWebsite triggers and movement speed following joystick "force", which is good for small displays because the normal walking speed is already too fast.

### CODE REVIEW

**Comment by pizkaz** [comment]
Hmm I have no idea what yarn is trying to tell me here. :-(
I back-ported these patches from our instance, which is running on Phaser 3.52.0. Could that be a problem?

**Comment by tabascoeye** [comment]
It wants ```"esModuleInterop": true,"``` in ```front/tsconfig.json```

**Comment by Kharhamel** [comment]
I think we will work on mobile support in our next sprint. Right now we are really focused on the payment features, so sorry if we don't yet give a lot of attention to this PR.

**Comment by pizkaz** [comment]
Superseded by #873

**Pull request closed without merging**
