### PR TITLE
Add workaround for #932

### PR DESCRIPTION
**Pull request by guysoft**
See https://github.com/thecodingmachine/workadventure/issues/932#issuecomment-830777306

### CODE REVIEW

**Comment by jonnytest1** [comment]
sudo docker-compose up --dorce-recreate is what i use

**Comment by guysoft** [comment]
@jonnytest1 Should I change it to that then? Should do the same thing

**Comment by jonnytest1** [comment]
sure 
oh its force-recreate 😅

**Comment by jonnytest1** [comment]
🤔 if you do some sneaky git changes while its running you might need to do it again 
 since the bakcend container can crash if the messages container isnt fast enough in generating the necessary files for compilation - if that happens it ownt even refresh anymore

**Comment by guysoft** [comment]
Sounds to me its best to keep this PR as is since its what I tested and we know that works.  Also when you stop and start you can.confirm the container indeed stopped

**Pull request merged**
