### PR TITLE
Updated favicons

### PR DESCRIPTION
**Pull request by ValdoTR**
Simple request to replace the current favicon "WA" with the coffee cup style favicon !

### CODE REVIEW

**Comment by ValdoTR** [comment]
Before
image


After
image

**Comment by moufmouf** [comment]
Hey Valdo,

Thanks a lot.
There is a slight problem: the image you uploaded are blurry: https://github.com/thecodingmachine/workadventure/blob/f7c45929449fae5e424f754475cae732496ebf5a/front/dist/static/images/favicons/ms-icon-150x150.png

Maybe you upscaled a small image?
Could you try to do the same thing, but with pixelated upscaling?

**Comment by ValdoTR** [comment]
Yeah... I noticed that but the source is [the official image from the site](https://workadventu.re/img/logo.png).
Do you have a logo with a better quality?

PS: For a favicon maybe it's not so important?

**Comment by moufmouf** [comment]
If you start with the small image and you use a "pixel art upscaler", this should work.
Like this one: https://lospec.com/pixel-art-scaler/

It's not only a favicon, it will also be the logo of our PWA in the future!

**Comment by ValdoTR** [comment]
Here we go @moufmouf!
Pixel-perfect and lightweight favicons for all sizes :)

**Comment by moufmouf** [comment]
Excellent! :+1:

**Comment by moufmouf** [comment]
@ValdoTR Can you also open a PR on the website (on Gitlab)

**Comment by ValdoTR** [comment]
I will do it.

**Pull request merged**
