### PR TITLE
Implement UI Website

### PR DESCRIPTION
**Pull request by nolway**
The UI Websites are a new way to implement a website on WorkAdventure.
Currently we have 3 way :
- Embed map websites
- Following websites (like the tutorial in scripting API extra)
- CoWebsites

This new way add the possibility to implement a website on the view-port and like a native UI element.
There are many case of usage like a pop-up on the middle of the page, an inventory (why not ;) ) or anything you to keep on the user interface during his adventure.

image

### CODE REVIEW

**Comment by Lurkars** [comment]
I know this is a bit Off topic, but I notice certain PRs like this, where at least from my perspective it is not clear, what the PR is about to implement. I don't know what a UI website is and even the screenshot does not clear anything up for me. So this is just a friendly request about more details on PRs. It will also makes things easier in future to look up commits etc.

**Comment by nolway** [comment]
Yes, I agree, I will add more information, by tomorrow.
I'm writing the documentation for this feature so I didn't put much info in it.
I just added the WIP tag to the pr name to inform it's status.

We will try to be more careful =)

**Review by moufmouf — COMMENTED** [review]
Excellent!

**Comment by moufmouf** [comment]
Also, an end-to-end test would be awesome!

**Comment by nolway** [comment]
I need to merge this, but the test is coming (I'll need your help to do it @moufmouf).

**Pull request merged**
