### PR TITLE
Twemoji emote menu

### PR DESCRIPTION
**Pull request by Lurkars**
This uses Twemoji Font to show Emotes and an Emoji Picker (emoji-button) for selecting emotes.

The positioning on initial opening is not ideal, I am not deep enough into phaser to understand what's going on there, so will need some tweaks, but in general I think it is usable and a good improvement.

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @Lurkars ,

Thanks a lot for this PR!

For the others, I'm putting a screenshot here:

image

I'll have to discuss with @Kharhamel and @gparant to see how we can integrate that.
Also, we would need to find a way to make the selection box not related to the zoom level (otherwise, usage on mobile will be complex)

**Comment by Lurkars** [comment]
Yes, I just copied the resize adjustments from the radial menu. Anyways I had focusing issues on mobile, so this definitely need more work on that.

**Comment by Kharhamel** [comment]
Since you created a new PR, can I close this one?

**Comment by Lurkars** [comment]
Closed in favour of #1437

**Pull request closed without merging**
