### PR TITLE
Mobile/touch support (2)

### PR DESCRIPTION
**Pull request by moufmouf**
This PR builds upon #803 and simply merges code developed meanwhile from develop branch.

A huge thanks to  @Palid, @tabascoeye and @pizkaz for this amazing work.

### CODE REVIEW

**Comment by pizkaz** [comment]
I have a polished version of this PR ready - rebased onto current develop branch. Shall I create a new PR?

**Comment by moufmouf** [comment]
@pizkaz Definitely.
Ping me in the PR and I'll close this one. We are going to work heavily on mobile support in the coming weeks and starting from your work will prove invaluable.

**Comment by pizkaz** [comment]
Superseded by #873

**Comment by moufmouf** [comment]
Thanks @pizkaz

**Pull request closed without merging**
