### PR TITLE
Removed hard coded default map

### PR DESCRIPTION
**Pull request by tbnobody**
You can apply local maps using the maps vhost as previously.
But it's also possible to specify external maps by prepending http or https.

### CODE REVIEW

**Comment by moufmouf** [comment]
Thanks for the PR!

Could I ask you to rename `URL_ROOM_STARTED` into `START_ROOM_URL`?

**Comment by tbnobody** [comment]
I can do this, not a problem. Just a remark, URL_ROOM_STARTED also occours in back/src/Enum/EnvironmentVariable.ts and pusher/src/Enum/EnvironmentVariable.ts.... Thats the reason I called it also like this in front/src/Enum/EnvironmentVariable.ts...
As far as I can see it, it's not used in back and pusher. 
Do you want me to name it START_ROOM_URL just in front or do you also want me to rename or remove it in back and pusher as well?

**Comment by moufmouf** [comment]
Oh, thanks!
Yes, please rename it to `START_ROOM_URL` and remove `URL_ROOM_STARTED` from pusher and back since they are not used anymore. Thanks a lot!

**Comment by moufmouf** [comment]
Merged! Thanks a lot @tbnobody !

**Pull request merged**
