### PR TITLE
Make Open back office configurable 

### PR DESCRIPTION
**Pull request by lochot**
add a env var to make it configurable. Let original workadventure url if empty. (#2966 )
(That is my first pull request, sorry if i did a mistake)

### CODE REVIEW

**Comment by moufmouf** [comment]
Thanks a lot @lochot !

I'm looking at this PR and I wonder if we are not following the wrong path here.

This is not about your code (your PR is fine). This is about these lines:

http://github.com/thecodingmachine/workadventure/blob/57c276133d9787f41a8844dfde22ebd5fe0dde69/play/src/front/Stores/GameStore.ts#L17-L22

Basically, the "Back office" menu is displayed only for users with the "admin" or "editor" tag.
In my opinion, this rule is specific to our SAAS admin. Other admins might want to implement different rules.

So in my opinion, instead of checking the user tags in the front, we could change the "/api/map" endpoint in the API to return the URL of the "Open back-office" button.

This way, the admin could decide the URL. Even better: depending on the user profile, the link to the back office could point to different URLs.

For instance:

GET `/api/map`

Response:
```
{
  // ...
  "backOfficeUrl": "https://mybackoffice.com/user/[userid]"
}
```

We can go even further. The link to "Register" is a special case of adding a button in action bar. We could make this even more generic. This way, we could add ANY button through the API. For instance:

GET `/api/map`

Response:
```
{
  // ...
  "actionBarCustomButtons": [
    {
      "type": "textButton",
      "label": "Access back-office",
      "url": "https://mybackoffice.com/user/[userid]"
    },
    {
      "type": "iconButton",
      "label": "Take a survey",
      "src": "https://.../survey.png",
      "url": "https://mybackoffice.com/survey"
    }

  ]
}
```

@gparant what do you think?

**Comment by moufmouf** [comment]
> I have an admin api (i made a wordpress plugin), all is good, and i want to use some functionnality like global messages that appear when i give the admin tag to a user, and when i give it, the hammer appear.

Got it!

Actually, in the future, I'd like to get rid of tags as much as possible in WorkAdventure.

> So i think we have to do a mix of those two solution ?

:+1:
We can keep the "admin" tag for the global messages (for now)
and we can rely only on a new "actionBarCustomButtons" property in the Admin API "/map" endpoint for displaying things in the menu.

That would solve your issue and would make WorkAdventure more configurable and more flexible for anyone.

**Comment by lochot** [comment]
Seems to be a good solution,

so if an admin_api_url, we can remove hammer button (and login and register too) and we add a new admin api/map field that can add button ?

@moufmouf , @gparant, [LindezaGrey](https://github.com/LindezaGrey)

(for my knowledge : 
- do we have to continue this conversation in the issue ?
- do have i to create a new branch with a new pull request ?)

**Comment by lochot** [comment]
let's go !

**Pull request closed without merging**
