### PR TITLE
fix(front): load correct char scene file

### PR DESCRIPTION
**Pull request by max-wittig**
Related to https://github.com/thecodingmachine/workadventure/issues/941

### CODE REVIEW

**Comment by max-wittig** [comment]
Tested locally

**Comment by max-wittig** [comment]
@Kharhamel Could you please take a quick look at this fix?

**Comment by jonnytest1** [comment]
> @Kharhamel Could you please take a quick look at this fix?

🤔 is this how it works ? i have 3 pull requests noones ever even seen

**Comment by max-wittig** [comment]
Try to delete the localStorage. All data. It will not work without it.

**Review by gparant — COMMENTED** [review]
Be careful, the file is : https://github.com/thecodingmachine/workadventure/blob/develop/front/dist/resources/html/selectCharacterScene.html, so `selectCharacterScene.html` is good

**Comment by gparant** [comment]
We fixed problem on last tag v1.3.4

**Comment by pizkaz** [comment]
> We fixed problem on last tag v1.3.4

So... Close? :-)

**Comment by max-wittig** [comment]
Fixed

**Pull request closed without merging**
