### PR TITLE
Map group layer support

### PR DESCRIPTION
**Pull request by Lurkars**
Don't know if this feature is wished, but in more complex maps, I would like to use the 'Group Layer' function of Tiled. This is useful for example grouping all functional layers like Jitsi, Audio or Website layer. For traversing the layer tree, I used recursion, so this lead to helper functions.
I did not cover the special case of the 'start' and 'floorLayer', so they should stay in root, because Phaser only accept complete path as names for layer.
The 'exitLayer' and 'startLayer' properties work fine.

### CODE REVIEW

**Comment by Lurkars** [comment]
I accidentally removed my branch on clean up, I think this automatically closed the PR.

**Comment by pizkaz** [comment]
We have been using this for a couple of weeks on multiple maps. Works like a charm. I would never want to build maps without layers again. :wink:

**Comment by moufmouf** [comment]
Hey @Lurkars ,

Thanks a lot for this PR.
It looks good. I have a feeling that we can make it even better. Each time we want to iterate over the layers, we would need to add a "xxxHelper" function using your technique. I wonder if we can implement a custom "iterator" over layers that iterates the list of layers in the correct order.
I'll try to start from your PR and see if I can manage to use iterators instead (I've never played with iterators in Typescript before, so this will be a first for me)

**Comment by moufmouf** [comment]
@Lurkars ,

I built upon your PR in #899. I'm simplifying part of the recursive code by creating an iterator (`LayersIterator`) in charge of flattening the maps.
Thanks a lot, I'd have a hard time understanding the logic of adding a prefix with '/' in the name of group layers if it was not for your work!

**Comment by moufmouf** [comment]
Integrated into #899
Thanks @Lurkars

**Comment by jonnytest1** [comment]
oh we can relatively easy 
exclude invisible layers now 
https://github.com/thecodingmachine/workadventure/issues/920

**Pull request closed without merging**
