### PR TITLE
Attempting to build only on AMD64 target

### PR DESCRIPTION
**Pull request by moufmouf**
This is an attempt to use a AMD64 image to generate proto files and also to build the application.

Benefits:

- The Dockerfile can again be "self-containing" (we don't need to preprocess the proto files before)
- The build will run faster (yeah!)

### CODE REVIEW

**Comment by moufmouf** [comment]
Ping @pizkaz .
This might be of interest to you as I think you reverted the PR that was adding Arm64 support in XCE because of this.
Now, we can have both ARM64 support and self-contained Docker builds

**Comment by pizkaz** [comment]
Sweet! \o/

Just rebased onto current `develop` branch and the docker build seems to work fine.
However, I'm now stuck in the "Waiting for connection" screen - same behavior on `xce` and `develop`. What am I doing wrong?

**Comment by moufmouf** [comment]
Weird. I just merged master into develop (a number of bugfixes) and it works for me. Can you give it a try again?

**Comment by pizkaz** [comment]
```
workadventure-back-1  | [ERROR] 09:03:27 ⨯ Unable to compile TypeScript:
workadventure-back-1  | src/Services/SocketManager.ts(3,5): error TS2724: '"../Messages/generated/messages_pb"' has no exported member named 'AnswerMessage'. Did you mean 'BanUserMessage'?
workadventure-back-1  | src/Services/SocketManager.ts(3,5): error TS2724: '"../Messages/generated/messages_pb"' has no exported member named 'AnswerMessage'. Did you mean 'BanUserMessage'?
workadventure-back-1  | src/Services/SocketManager.ts(18,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'JitsiJwtAnswer'.
workadventure-back-1  | src/Services/SocketManager.ts(19,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'JitsiJwtQuery'.
workadventure-back-1  | src/Services/SocketManager.ts(20,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'JoinBBBMeetingAnswer'.
workadventure-back-1  | src/Services/SocketManager.ts(21,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'JoinBBBMeetingQuery'.
workadventure-back-1  | src/Services/SocketManager.ts(26,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'QueryMessage'.
workadventure-back-1  | src/Services/SocketManager.ts(605,27): error TS2322: Type 'any' is not assignable to type 'never'.
workadventure-back-1  | src/Services/SocketManager.ts(618,31): error TS2551: Property 'setAnswermessage' does not exist on type 'ServerToClientMessage'. Did you mean 'setBanusermessage'?
```

**Comment by moufmouf** [comment]
Anything special in the `pusher` or `back` logs?

**Pull request merged**
