### PR TITLE
Fix GDPR violations (loading external resources)

### LINKED ISSUE #1668: clear up usage of webpack vs CDNs
It seems weird that some resources are taken from external sources (CDNs) while almost everything is cleanly referenced and managed by webpack.

This should be either be made configurable for self-hosters (i.e. config options: "no external resources" vs. "save my bandwidth!") or be taken to one of both philosophies fully.

The things I noticed being taken from etxternal CDNs are:
* NES.css
* Quill.js
* Twemoji

likely there is more.

==> personally I would love a self-contained WA server, which only accesses TURN and jitsi as external sources.

### PR DESCRIPTION
**Pull request by pizkaz**
Fixes #1668 and another GDPR violation (unconditionally loading embedly without asking for consent).

### CODE REVIEW

**Comment by moufmouf** [comment]
Gee! You are right about Embedly. Damn it!
But we need somehow to keep the feature available.

Either by making this optional (behind an environment variable flag maybe?) or by replacing it with a self-hostable open--source alternative (that would be the best idea).

@cesar-cardinale I know you started investigating Embedly alternatives. Any idea?

**Comment by cesar-cardinale** [comment]
> Gee! You are right about Embedly. Damn it! But we need somehow to keep the feature available.
> 
> Either by making this optional (behind an environment variable flag maybe?) or by replacing it with a self-hostable open--source alternative (that would be the best idea).
> 
> @cesar-cardinale I know you started investigating Embedly alternatives. Any idea?

In fact Embedly is not used at this point. We have disabled it. The free version is not really a good choice. I didn't find a good solution for this problem, maybe we need to implement our own solution ?

**Comment by moufmouf** [comment]
Maybe building something on top of lib that scrapes info from an HTML page?

Something like this: https://www.npmjs.com/package/open-graph-scraper ?

**Comment by moufmouf** [comment]
Another possible contender for the library to fetch metadata: https://www.npmjs.com/package/metascraper

**Comment by moufmouf** [comment]
Commits where cherry-picked as part of v1.14.14.

Closing. Thanks @pizkaz !

**Pull request closed without merging**
