### PR TITLE
Clarify layer on which the popup rectangle should be created in Update api-ui.md

### PR DESCRIPTION
**Pull request by Ennoriel**

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @Ennoriel ,

According to #2497 (that adds a test map for this use case), it seems that the "areas" are already read from any object layer in Tiled.
So I'm wondering: how / when did you face this problem? Can you provide us with a map to reproduce the issue?

**Comment by Ennoriel** [comment]
Hey @moufmouf !

I made a repro repo here https://github.com/Ennoriel/workadventure-map-ui-bug. I changed the clock rectangle to another layer and it's not working anymore.

**Comment by moufmouf** [comment]
Thanks a lot @Ennoriel .
@Waclaw-I Can I ask you to take a look at the repo?

**Comment by Waclaw-I** [comment]
It is indeed correct.

For opening the popup, we are looking for an object of specific name, on layer with both `objectgroup` type and `floorLayer` name, see below:
```
if (layer.type === "objectgroup" && layer.name === "floorLayer") {
```
[in the code](https://github.com/thecodingmachine/workadventure/blob/e75a52ac69ef2ad8f3d2fd4a6f8a928003165ebf/front/src/Phaser/Game/GameScene.ts#L2511)

It has nothing to do with Area objects though.

Cheers

**Pull request closed without merging**
