### PR TITLE
Adding missing Content-Type header for json responses in pusher code

### PR DESCRIPTION
**Pull request by lbehm**
Removes the parser warnings in the console due to missing 'Content-Type' headers of some json responses.

### CODE REVIEW

**Comment by moufmouf** [comment]
Thanks a lot! :+1:

Would you mind running "yarn run pretty" on the pusher to fix the linting issues?
I'll merge this right afterwards!

**Comment by lbehm** [comment]
Huh, I guess I have to check if that's included in my build.

On the topic of styling I would rather recommend to use an abstraction on top of `HttpResponse` that supports `.json()` which would set necessary headers.

**Comment by moufmouf** [comment]
> On the topic of styling I would rather recommend to use an abstraction on top of HttpResponse that supports .json() which would set necessary headers.

Alas, I have to use µWebsockets (because the pusher needs an implementation that is very performant). µWebsockets is very low level (unlike Express for instance), and we'd probably have to develop that abstraction ourselves.

**Comment by lbehm** [comment]
µWebsockets is great! But like most c++ tools, they're mostly just an awesome bare minimum baseline that you can build customized stuff on top. I was thinking more along the lines what [this project](https://github.com/colyseus/uWebSockets-express) did. But I'm just talking about a tiny wrapper for setting repetitive stuff, not an entire api layer! But please don't listen to me, I'm a c++ and not a js dev!

Back on topic: I still can't figure out how to setup my environment to overcome that `error Command "prettier" not found.`
I run basically that release compose file, so I guess I have to figure out what the .yaml mentioned in your readme tries to do... Is the actual magic in the base image or the stuff that comes from messages? Thank you in advance!

**Comment by moufmouf** [comment]
Woooh, I was not aware of https://github.com/colyseus /
[uWebSockets-express](https://github.com/colyseus/uWebSockets-express) (I think it did not exist yet when we migrated to µWebsockets!

Thanks a lot for the pointer, I'll definitely take a look at it!

Regarding prettier, I usually run:

```
docker-compose up
docker-compose exec front yarn run pretty
```

But I can run that myself, don't worry :)

**Comment by moufmouf** [comment]
Just opened this issue to keep track of using a better abstraction: https://github.com/thecodingmachine/workadventure/issues/1877

**Pull request merged**
