### PR TITLE
Fix CustomizeScene killing CPU

### LINKED ISSUE #518: CustomizeScene.ts killing browser on horizontal movement
It seems that after 1.0 refactors there have been some leftover parts killing performance.

Function

```
    private moveCursorHorizontally(index: number): void {
        this.selectedLayers[this.activeRow] += index;
        if (this.selectedLayers[this.activeRow] < 0) {
            this.selectedLayers[this.activeRow] = 0
        } else if(this.selectedLayers[this.activeRow] > this.layers[this.activeRow].length - 1) {
            this.selectedLayers[this.activeRow] = this.layers[this.activeRow].length - 1
        }
        this.moveLayers();
        this.updateSelectedLayer();
        this.saveInLocalStorage();
    }
```

The culprit is this function: call: `this.updateSelectedLayer();`, which ends up in infinite asynchronous loop. Removing it fixes the problem.

### PR DESCRIPTION
**Pull request by Palid**
Fixes #518

### CODE REVIEW

**Comment by moufmouf** [comment]
Oh! I had been wondering since several weeks what was going wrong here. Thanks a lot @Palid !

I'll properly review this tomorrow before merging this. Thanks again!

**Comment by Palid** [comment]
From what I saw the browser can still be killed after leaving CustomizeScene, unfortunately.

**Comment by Kharhamel** [comment]
How exactly does changing the listened input fix the issue? Also do you want us to merge this now or do you still plan to add more changes?

**Comment by Palid** [comment]
@Kharhamel this fixed the issue by enforcing debouncing of the events via listening only to keyup instead. Proper fix should probably have some deboucing on keydown, but this is a good 80/20 fix I'd say.

I'm a bit too tired to properly fix the latter part (sometimes crashing after choosing custom character), but I'll probably do the fix for it later, so let's merge this and later get second part of it.

**Pull request merged**
