### PR TITLE
Feat/use env variable for empty start map

### PR DESCRIPTION
**Pull request by VanFanelia**
I startet to create a production docker-compose file.
The first problem i solved was, that you can configure the default start map.

This is a merge request to give this feature back to the origin repository

Greetings,
Van

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @VanFanelia !

Thanks for this PR.

Defining the `PATH_TO_START_MAP` is a good idea!
However, the default value you are putting is:

```
PATH_TO_START_MAP=/Floor0/floor0.json
```

It would make more sense to be able to define a complete URL, don't you think? Something like:

```
PATH_TO_START_MAP=/_/mymap.github.io/myuser/map.json
```

I'm not 100% sure but with your proposal, it seems the map must be put in the "/maps" directory and cannot be hosted anywhere. Am I right?

**Comment by VanFanelia** [comment]
Already fixed that problem in another feature branch, that you can use a /_/global/ link for this varible. how can i merge 2 pull request together 2 one?

**Comment by moufmouf** [comment]
I'd do something like this:

```
git checkout feat/use-env-variable-for-empty-start-map
git merge [your other branch]
git push
```

(or you can close this PR and open another PR from your other branch, that works too)

**Comment by moufmouf** [comment]
Hey @VanFanelia ,

Thanks a lot for your work and suggestion :+1:
I'm closing this as it has been superseded by https://github.com/thecodingmachine/workadventure/pull/571.

**Pull request closed without merging**
