### PR TITLE
Mobile/touch support

### PR DESCRIPTION
**Pull request by pizkaz**
Rebase of #803 

This combined work by @Palid, @tabascoeye and @pizkaz integrates a software joystick and adds touch support to login scenes.
With this patch set it is possible to use Workadventure on touch devices. \o/

Contrary to what commit metadata says, @Palid did most of the work for rC3. @tabascoeye and myself maintained the patches, tweaked stuff and implemented touch support for Jitsi/openWebsite triggers and movement speed following joystick "force", which is good for small displays because the normal walking speed is already too fast.

### CODE REVIEW

**Comment by pizkaz** [comment]
Ping @moufmouf

**Comment by pizkaz** [comment]
There is one slight problem with this code: The joystick is drawn below the `floorLayer`. I'm thinking about removing the visual representation of the joystick completely and also enabling it per default. What do you think?

**Comment by pizkaz** [comment]
> There is one slight problem with this code: The joystick is drawn below the `floorLayer`. I'm thinking about removing the visual representation of the joystick completely and also enabling it per default. What do you think?

Oops, forgot to mention that this was done. :smile_cat: 

You can now touch and drag anywhere on the map to move around. I also added a "toggle fullscreen" button in the game menu, because on small displays every pixel counts. :wink:

**Comment by Kharhamel** [comment]
I think we are going to merge this into develop. Then we will fix the minor issues in independent MR. @pizkaz can you fix the conflicts? If not I will do it quickly

**Comment by pizkaz** [comment]
Rebased onto current `develop` and added touch support for the new "select companion" scene.

**Comment by mhupfauer** [comment]
Pet selection does not yet support touch support leaving users in a "locked" state

**Comment by pizkaz** [comment]
Hmm, that's odd. It's working in XCE. Maybe it's due to the different Phaser versions again..?

**Comment by mhupfauer** [comment]
@pizkaz Even on XCE it is not working properly. A user can select a companion but is required to "PRESS ENTER TO START" however there is no keyboard input and "tapping" on "PRESS ENTER TO START" like in character selection is not working.

**Comment by pizkaz** [comment]
Are you sure you
1. have e75fb9a6a9abc72468dc2545432ffb32d7d9baca in your branch and
2. build the front container from source?

**Comment by mhupfauer** [comment]
@pizkaz 
I see e75fb9a is not yet merged downstream to XCE. However rebuilding cleanly introduced the changes and it works now.

**Comment by Kharhamel** [comment]
I'll look into this

**Comment by pizkaz** [comment]
> @pizkaz
> I see [e75fb9a](https://github.com/thecodingmachine/workadventure/commit/e75fb9a6a9abc72468dc2545432ffb32d7d9baca) is not yet merged downstream to XCE.

Indeed. I'm waiting for #893 to get merged and will do a fresh rebase when it's done. :-)

**Pull request merged**
