### PR TITLE
Adding the ability to inject websites directly inside maps

### PR DESCRIPTION
**Pull request by moufmouf**
This PR adds the ability to inject a website INSIDE a map (as an iframe inside a Phaser HTML object)
The iFrame will be rendered transparently, unless you set a background-color on the body, which opens a number of cool possibilities.

To be done:

- [x] allowing the Iframe API in those iframes
- [x] adding this to the scripting API (add, remove, change URL, set visibility, etc...) (can be done in another PR)

### CODE REVIEW

**Comment by moufmouf** [comment]
image

**Comment by jonnytest1** [comment]
while you're at it maybe add an option to add the iframe as an overlay

**Comment by moufmouf** [comment]
@jonnytest1 what do you mean by "overlay"?

**Comment by jonnytest1** [comment]
transparent background nad fixed above the map to make stuff like ui

**Comment by moufmouf** [comment]
> transparent background nad fixed above the map to make stuff like ui

Oh, that would be sweet :D

I'll wait for that a bit before and will do it in another PR. I think the positioning of the iframe in the UI might be a bit tricky (because we have to care for responsiveness). And I'm not sure how to to it properly.

**Pull request merged**
