### PR TITLE
Multi-platform images

### LINKED ISSUE #800: Unable to run on a Raspberry Pi 4
I am trying to run WorkAdventure on a Raspberry Pi 4. I have git cloned the repository and launched a docker-compose up in order to start all the containers. Unfortunately, I get the following errors:

I suspect it is caused by a difference of platform since Raspberry Pis are ARM based. Can someone confirm?

Does someone have a workaround? Should I build all the images and in this case how to do such a thing?

Thanks for the help

### PR DESCRIPTION
**Pull request by lukashass**
Closes #800 

Updates [docker/build-push-action](https://github.com/docker/build-push-action) to v2 and enables multi-platform (amd64, arm64) docker builds for:

- [x] front
- [x] back
- [x] pusher
- ~uploader~
- ~maps?~

Moves building message types out of the Dockerfile since building those does not work on arm64.

~Depends on #1922. Please merge it first!~

:jack_o_lantern: Please squash this :jack_o_lantern: 

### TODO

- [x] migrate `add_git_labels`?
- ~set tags with metadata action~ (`rlespinasse/github-slug-action` is used in deploy job as well so better keep it in build job for consistency)

### Follow-up

- move building out of Dockerfiles and enable Github Action caching to speed things up

### CODE REVIEW

**Comment by lukashass** [comment]
Building WorkAdventure for 32bit Arm is not straightforward since `uWebSockets.js` does not distribute 32bit Arm binaries (https://github.com/uNetworking/uWebSockets.js/tree/binaries):

```
Status: Downloaded newer image for thecodingmachine/workadventure-pusher:multi-platform-images
/usr/src/node_modules/uWebSockets.js/uws.js:22
		throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
		^

Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_arm_83.node'
Require stack:
- /usr/src/node_modules/uWebSockets.js/uws.js
- /usr/src/dist/src/Server/server/app.js
- /usr/src/dist/src/Server/sifrr.server.js
- /usr/src/dist/src/App.js
- /usr/src/dist/server.js
    at /usr/src/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/usr/src/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/dist/src/Server/server/app.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

**Comment by lukashass** [comment]
@moufmouf Regarding [012413a](https://github.com/thecodingmachine/workadventure/pull/1924/commits/012413ad64b7c69881d3cf92078feec4aa27fe6a), I was actually planning to move all builds out of the Dockerfiles. That will significantly speed up the build on other architectures since it will only be copying build artifacts into the image. Docker layer caching can then be replaced by Github Actions caching.

**Comment by moufmouf** [comment]
@lukashass I'm not sure how I feel about moving the builds out of Dockerfiles. Sure, it is all automated in the CI, but still, I like the fact that a Dockerfile can build an image in a "self-contained" way. I'll need to think about this.

**Comment by moufmouf** [comment]
@lukashass I understand better now! Images are built in the same job so the build time is really longer now.
I'm wondering. Instead of building out of the Dockerfile, could we simply run several jobs in parallel (one per build target?)

Another question: @pizkaz I see you reverted the commit in XCE. Any particular reason?

**Comment by pizkaz** [comment]
Yes, right now it breaks the Docker image build because generated protobuf message files are missing.
IMHO, creating .env  and running `docker-compose up` should be the only thing necessary to start everything.

**Comment by sknebel** [comment]
> IMHO, creating .env and running docker-compose up should be the only thing necessary to start everything.

I know at least two deployments that currently rely on that, and a third I'm fairly sure it does (/cc @lbehm re kraut.world). One option could be making dockerfiles that handle it on x86/x86_64 and only need extra steps on ARM? Or shipping the compiled protobufs in the repo? (e.g. through CI that automatically pushes them?)

**Pull request merged**
