### PR TITLE
prettier config

### PR DESCRIPTION
**Pull request by jonnytest1**

### CODE REVIEW

**Comment by jonnytest1** [comment]
🤔 i think pretteir itself doenst even do memeber ordering

**Comment by moufmouf** [comment]
Yes. Prettier seems to not touch the AST at all by default => https://github.com/prettier/prettier/issues/949#issuecomment-285097994

**Comment by jonnytest1** [comment]
yeah im currently checking if i cna add that to eslint - 🤔 first i gotta get eslint to run again :D

**Comment by moufmouf** [comment]
Yeah, validation server-side is in this PR: https://github.com/thecodingmachine/workadventure/pull/1226

**Comment by jonnytest1** [comment]
with server side i mean on the git server

**Comment by moufmouf** [comment]
Oh, ok!
#1226 is actually running Prettier on the pusher and back in CI.
For the front part, I think we need to wait a bit. My idea was to only run it on modified files (in a precommit hook) for a few month, to avoid triggering a shitload of conflicts in open PRs (that are mostly in front, and not so much on pusher and back)

Then, after a few months, we can enable Prettier in CI on front too.

**Comment by moufmouf** [comment]
According to https://prettier.io/docs/en/integrating-with-linters.html, we should probably avoid running prettier as an eslint plugin.

So the solution will probably be to configure prettier, and put the AST modifying plugins (like import reordering) in eslint, then running both.

**Comment by jonnytest1** [comment]
ok import ordering works  in eslint now we just need to run eslint on the stages files as well

**Comment by jonnytest1** [comment]
lul that is goinbg to be so annoying :D

**Comment by jonnytest1** [comment]
os stil lsmall problem - when the linting fails it should not commit currently it still does 🤔

**Comment by jonnytest1** [comment]
🤔 i should disable autopush until it works ^^

**Comment by jonnytest1** [comment]
didnt find the setting

**Comment by jonnytest1** [comment]
"Reverting to original state because of errors..." now that is annoying for an autofixing precommit hook

**Comment by jonnytest1** [comment]
... ok um so i fixed eslint 😅

**Comment by Kharhamel** [comment]
I am closing this since most of the work is in #1230

**Pull request closed without merging**
