### PR TITLE
Add missing layer properties

### LINKED ISSUE #1256: Second layer object is not using opacity
Hi,

I tried to use a second object layer, to add some information on my different zone.

image

In tiled, i export the map as an image, so i can share this informational picture to the people that are using this map.

I tried to use opacity to 0 in this specific layer, so it should not be shown on the map.
But the opacity seems to not working as the texts are still shown.

image

Do you think you could do something for this bug ?

Having the ability to make a "map of the map" to help people is really usefull for me.

### PR DESCRIPTION
**Pull request by Chasethechicken**
Enables map makers to set the alpha, visibility, origin and size of layers.

Based on this PR: #1260, but removes changes to the linter configuration and adds a test map.

Fixes #1256.

Created this as a draft, as I haven't actually tested this yet.

### CODE REVIEW

**Comment by moufmouf** [comment]
Thanks for the PR!
Would you mind adding a reference to the test file in `/maps/tests/index.html` (it is the file linking to all the test maps) and also,
on the test map, adding a text object with a small text explaining the test case with the expected behaviour?

**Comment by Chasethechicken** [comment]
I have added the map to the html and added some text with expected behaviour.
I have also fixed a typo, so it now actually compiles. :sweat_smile: 
And I have managed to test it locally and verified it works as intended.

**Comment by moufmouf** [comment]
Thanks a lot!

**Comment by moufmouf** [comment]
@Chasethechicken Sorry to bother you on this old PR. I have a question coming to my mind.
In the test map you provided, there is a layer that does not have the same size as the other layers (all layers are 9x9 but the layer with the plant is 3x3).

I wonder how you managed to create this layer. In Tiled, there does not seem to be an option allowing me to resize an individual layer. And yet, you have one here. How did you manage to create this map? What am I missing? :D

**Comment by Chasethechicken** [comment]
@moufmouf Sorry for the late reply.
I can't remember for sure, but I think I just edited the json manually.
Tiled is able to import that, it just lacks the UI to create such a layer.

**Pull request merged**
