### PR TITLE
Fix volume slider UI updates

### LINKED ISSUE #801: Volume sound / music property ?
Hi,

As i am using some ambient sounds in my maps, will it be possible to set the volume of a sound with a property ?

### PR DESCRIPTION
**Pull request by pizkaz**
Fixes #801 again.

### CODE REVIEW

**Comment by pizkaz** [comment]
Is there anything preventing this fix from being merged? :-)

**Comment by Lurkars** [comment]
I commented on code that the local storage volume get totally ignored. If this is a fix of another issue, than we have a conflict of two functionalities and another solution is required! Also value get still stored, so map property overwrite user settings!

I think in old player, the audioVolume property was also check against the local storage, so if I manually set volume to 0.5 only map property values <= 0.5 would get applied.

From a UX perspective for now, I think ignoring local storage is a huge mistake. When I don't want to get too much noise from WA and set volume down and after next login or just forced by a map creator getting 100% is really annoying.

**Comment by pizkaz** [comment]
Hmm, you're right. I'll see if I can come up with a solution that respects local storage value *and* updates UI correctly.

**Comment by pizkaz** [comment]
Actually, since 8c3b70898142df5a6d59e9098bf3a3bd699e3bdd local storage volume is the *only* thing that sets volume. Map properties are completely ignored.

The updated patch respects both again and sets audio volume to the lower value.
As a side-effect, however, local storage volume is also updated if the map property value is lower than the one in local storage.
With this Svelte `createAudioManagerVolumeStore` thingy I don't see a easy/pretty solution except for introduction of another variable and a whole lotta logic. Don't know if it's worth it, though.

**Comment by Lurkars** [comment]
Tested it locally. Seems pretty fine to me! @moufmouf

**Comment by pizkaz** [comment]
Nice, svelte templates are now prettyfied as well!

That being said...

I *do* have things to do besides rebasing and porting the same commit over and over again.
Could we please merge this? Pretty please? :wink:

**Comment by moufmouf** [comment]
Really sorry about our lack of reactivity.

Let's merge this, this PR is perfect!

:+1:

**Comment by pizkaz** [comment]
No hard feelings. I can't imagine how many context switches per second you guys have regarding this project. :wink:

**Pull request merged**
