### PR TITLE
Actions menu api

### PR DESCRIPTION
**Pull request by Waclaw-I**
https://user-images.githubusercontent.com/14911927/154086850-bfbeb987-3087-4c13-b4cd-468806902f2a.mp4

- Register actions by using:
`WA.utils.addActionsMenuKeyToRemotePlayer(playerID: number, actionKey: string)`
- Unregister actions by using:
`WA.utils.removeActionsMenuKeyToRemotePlayer(playerID: number, actionKey: string)`

On script side:
- Create action logic to be triggered:
```
const actions = {
        'Ask to tell a joke': () => {
            console.log("Why don't scientists trust atoms?");
            setTimeout(() => { console.log('...'); }, 1000);
            setTimeout(() => { console.log('...'); }, 2000);
            setTimeout(() => { console.log('BECAUSE THEY MAKE UP EVERYTHING!') }, 3000);
        },
}
```
- Register custom action keys:
```
                WA.utils.onRemotePlayerClicked.subscribe((data) => {
                    lastRemotePlayerClicked = data.id;
                    WA.utils.addActionsMenuKeyToRemotePlayer(data.id, 'Ask to tell a joke');
                });
```
- Listen to ActionsMenuClicked trigger:
```
                WA.utils.onActionsMenuActionClicked.subscribe((data) => {
                    const action = actions[data.actionName];
                    if (action) {
                        action();
                    }
                });
```

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @Waclaw-I ,

Thanks a lot!

Now that I look at your PR, I think we can improve a bit the signatures of the API.

First of all, as much as possible, it would be great to avoid a `utils` namespace. Because it will end up growing indefinitely.

Since this is related to the UI (somehow), we could maybe put `onRemotePlayerClicked` inside the `WA.ui`?

Then, I think we can offer the developers a much smoother experience if the callback of `onRemotePlayerClicked` was passed an object. Something like:

```ts
WA.ui.onRemotePlayerClicked((remotePlayer: RemotePlayer) => {
    //
});
```

with:

```ts
class RemotePlayer {
      private id: string;
      public function addActionMenu(label: string, callback: () => void): ActionMenu;
}

class ActionMenu {
    public function remove();
}
```

Therefore, the whole developer experience would look something like this:

```ts
WA.ui.onRemotePlayerClicked((remotePlayer: RemotePlayer) => {
    const menu = remotePlayer.addActionMenu("This menu will self-destruct in 3 seconds", () => {
        console.log("Yeah!");
    });
    setTimeout(() => {
        menu.remove();
    }, 3000);
});
```

From an implementation point of view, we already used some custom objects in the API side.
Check out `front/src/Api/iframe/sound.ts` or `front/src/Api/iframe/website.ts`

**Comment by tabascoeye** [comment]
doesn't this conflict with the visit card feature?

**Comment by Waclaw-I** [comment]
> doesn't this conflict with the visit card feature?

Business Card and Block player are 'default' actions, always provided by the menu :)

**Comment by tabascoeye** [comment]
Ah sorry. I missed that the menu is now standard

**Comment by moufmouf** [comment]
@Waclaw-I One last thing before I merge this:

On the test map, could you write a text explaining what the test user is supposed to see and do? (connect with 2 people, click on the other player, etc...)

**Pull request merged**
