### PR TITLE
back,pusher,uploader: cleanup dependencies

### PR DESCRIPTION
**Pull request by Informatic**
Move typescript/ts-node-dev to dev dependencies, remove unused
dependencies.

### CODE REVIEW

**Comment by Kharhamel** [comment]
@tabascoeye  Thanks! I will merge this as soon as you resolve the conflicts.

**Comment by Kharhamel** [comment]
@Informatic are you still here?

**Comment by Informatic** [comment]
Sure, need anything?

**Comment by Kharhamel** [comment]
Sorry, I completly forgot  about this PR. This looks good now

**Pull request merged**
