### PR TITLE
Update Loading page

### PR DESCRIPTION
**Pull request by gparant**
Add WorkAdventure LOGO

### CODE REVIEW

**Comment by moufmouf** [comment]
This seems to be failing:
image

**Comment by gparant** [comment]
> This seems to be failing:
> image

I think that I will verify if the logo is loaded and is not, show loading text.

**Comment by moufmouf** [comment]
Top! :+1:

**Comment by moufmouf** [comment]
Note: I think we could do even better:

- [ ] Better centering of the logo and loading block vertically
- [ ] The loading progress bar should not be that thick and should not take the whole width of the screen (maybe 1/3 of the screen and 32px height?)

**Review by moufmouf — APPROVED** [review]

**Pull request merged**
